// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gerenciamento_financeiro_asp_net.Data;

#nullable disable

namespace gerenciamento_financeiro_asp_net.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241220190738_CriandoTabelas")]
    partial class CriandoTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gerenciamento_financeiro_asp_net.Models.Categoria", b =>
                {
                    b.Property<string>("CategoriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = "educacao",
                            Nome = "Educação"
                        },
                        new
                        {
                            CategoriaId = "salario",
                            Nome = "Salário"
                        },
                        new
                        {
                            CategoriaId = "viagem",
                            Nome = "Viagem"
                        },
                        new
                        {
                            CategoriaId = "mercado",
                            Nome = "Mercado"
                        },
                        new
                        {
                            CategoriaId = "comissao",
                            Nome = "Comissão"
                        });
                });

            modelBuilder.Entity("gerenciamento_financeiro_asp_net.Models.Financeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataDaOperacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransacaoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TransacaoId");

                    b.ToTable("Financas");
                });

            modelBuilder.Entity("gerenciamento_financeiro_asp_net.Models.Transacao", b =>
                {
                    b.Property<string>("TransacaoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransacaoId");

                    b.ToTable("Transacoes");

                    b.HasData(
                        new
                        {
                            TransacaoId = "ganho",
                            Nome = "Ganho"
                        },
                        new
                        {
                            TransacaoId = "gasto",
                            Nome = "Gasto"
                        });
                });

            modelBuilder.Entity("gerenciamento_financeiro_asp_net.Models.Financeiro", b =>
                {
                    b.HasOne("gerenciamento_financeiro_asp_net.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gerenciamento_financeiro_asp_net.Models.Transacao", "Transacao")
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Transacao");
                });
#pragma warning restore 612, 618
        }
    }
}
